### ISSUE TITLE
Enable configuring icons for different type of nodes

### ISSUE THREAD

**Issue by joonaruutiainen** [joonaruutiainen/interactive-process-graphs#14]
**Description.**
Nodes should be displayed in the graph with type-specific icons that can be defined during the graph configuration. If no icon is defined for a node type, a default icon is used.

**Definition of Done**
When configuring the graph component for an application, a set of icons to be used for different node types can be defined and they are displayed in the rendered graph.

**Time estimate**
15h

**Checklist**
- [ ] Get a test set of node icons to be used in the development
- [ ] Implement icon configuration for the graph component
- [ ] Default icon size? Resizing?
- [ ] Testing

**Additional notes and assumptions**
If desired, the group can make a default set of icons for common node types.

**Comment by vade123** [comment]
Work started in issue #64
