### ISSUE TITLE
Make processview zoomable

### ISSUE THREAD

**Issue by Tumpbe** [joonaruutiainen/interactive-process-graphs#9]
**Description.**
Make view zoomable with buttons and ctrl + scroll wheel

**Definition of Done**
View is zoomable with mouse scroll wheel and zoom buttons and approved by other group members

**Time estimate**
4h

**Checklist**
- [x] Add zoom buttons
- [x] Scroll wheel possibility
- [ ] Group member opinions
- [ ] Possible changes if needed

**Comment by joonaruutiainen** [comment]
Basic zooming is already implemented in the Reaflow canvas component that is being used for drawing graphs.
Issue closed for sprint 1 and feature enhancement moved to a new issue #46
